### ISSUE TITLE
Error Message Regarding Token

### ISSUE THREAD

**Issue by shafferb1** [petslane/php-bondora-api#1]
Firstly, thank you so much for creating this code. Incredible!

Secondly, I am trying to use it with the example on the readme documentation, but keep getting the error message:
Array ( [error] => invalid_request [error_description] => Required 'refresh_token' parameter is not set )

PHP Fatal error:  Uncaught exception 'Petslane\Bondora\ApiCriticalException' with message 'invalid_request: Required 'refresh_token' parameter is not set' in C:\Inetpub\vhosts\dd.com\dd\callback\src\Api.php:275
Stack trace:
#0 C:\Inetpub\vhosts\dd.com\dd\callback\index.php(28): Petslane\Bondora\Api->getToken(NULL)
#1 {main}
  thrown in C:\Inetpub\vhosts\dd.com\dd\callback\src\Api.php on line 275

I am using the following details:

$config = array(
    'auth' => array(
        'url_base' => 'https://www.bondora.com',
        'client_id' => 'xxxxx',
        'secret' => 'yyyyy',
        'scope' => 'BidsEdit BidsRead Investments SmBuy SmSell',
    ),
    'api_base' => 'https://api.bondora.com',

can you help me with where I am going wrong?

Thank you.

**Comment by petslane** [comment]
Hi, from trace i can see that you are using `getToken` method without any parameter. 
First, you have to go to url you get from `getAuthUrl()`, log in and bondora will redirect you to your site with code in url. You then use that code with `getToken` method to get accessToken.

**Comment by shafferb1** [comment]
Thanks for getting back to me. I had thought that the example code was complete. Have now got past that stage...

**Comment by petslane** [comment]
Well, there is comment before `getToken` sample that explains where you get that `$code`. I can't provide valid codes and tokens for example.

Anyway, this _"Required 'refresh_token' parameter is not set"_ error message that Bondora return is invalid. It's says 'refresh_token', but should be 'Authorization code'. I added check to throw exception before actually doing anything, if using `getToken` or `refreshToken` without providing `$code` or `$refresh_token`, so it would be more clear what went wrong.

Commit: https://github.com/petslane/php-bondora-api/commit/b1ae2e1f69795c89200fea0a5201649b639eabba

**Comment by shafferb1** [comment]
Please let me know if this is not the 'proper' way that I am supposed to be communicating. I'm kinda new to this.

Not having a success with:

bids($bidStatusCode=2, $startDate='2014-02-25 10:29:03', $endDate='2017-02-25 10:29:03', $pageSize=1, $pageNr=1)

I am getting a proper response:

Array ( [PageSize] => 1 [PageNr] => 1 [TotalCount] => 0 [Count] => 0 [Payload] => Array ( ) [Success] => 1 [Errors] => )

but it is not picking up on any of my bids. I have tried with all of the bidStatusCode in case that was the reason.

Have you had luck or is Bondora broke?

**Comment by petslane** [comment]
you should not specify parameter names that you are passing to method. just use values:
`bids(2, '2014-02-25 10:29:03', '2017-02-25 10:29:03', 1, 1)`
But I think that maybe status code is incorrect. `bids()` does not require and parameters, so you could try to call it without any parameters and check the status of your bid you are looking for.

**Comment by shafferb1** [comment]
Sorry, I must have edited after you read it. I also tried:
$api->Bids();
and had the same response.

**Comment by petslane** [comment]
How did you made a bid you are looking for? `$api->bids()` returns only bids made with api. If you made a bid on Bondora website, then you can not see that bid with api.

**Comment by shafferb1** [comment]
Thank you. That was my error :)
