### ISSUE TITLE
Thanks :)

### ISSUE THREAD

**Issue by spekulatius** [petslane/php-bondora-api#3]
Hello @petslane 

thank you for this lib. Very useful for my current automation of my Bondora portfolio. One quick question: I've seen you added the different coded states into Enum classes and then in constants. How did you intended these values to be used when mapping back? For example I get 0, 1 or 2 for the gender but when mapping these back to the labels I've to add my own mapping methods... Do I miss something here?

Peter

**Comment by petslane** [comment]
Hi!

What do you mean by mapping back?
If you get gender, then you can do `if ($gender == Enum\Sex::Unknown) {...`.
Not sure what mapping methods are you using...

**Comment by spekulatius** [comment]
Yeah, I'm keen to avoid a additional, long section with an if/switch and have a simply method call instead. Something like 

    echo $this->mapGender($response->Gender);  // turns 0 into "male", ...

**Comment by petslane** [comment]
If you need to display word "male" somewhere, then yes, you have to implement your own mapper that converts `Enum\Sex` constants to some strings. But in code, if you need to do some gender checks then it's better to check against `Enum\Sex::Male` constant than `"male"` string.

**Comment by renekorss** [comment]
@spekulatius 
Easiest solution would be:

````php
$refl = new \ReflectionClass('Petslane\Bondora\Enum\Sex');
$reverseMapping = array_flip($refl->getConstants());

echo $reverseMapping[0]; // Male
echo $reverseMapping[1]; // Female
echo $reverseMapping[2]; // Unknown
````
````php
// In your case
$genderString = $reverseMapping[$response->Gender]; // turns 0 into "male", ...
````

Of course you could do some function and check if there is such array key etc. But you get the point.

**Comment by spekulatius** [comment]
Thanks @renekorss. Much easier than the approach I would have went for.
